global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'chat-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['chat-service:8002']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

